<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class ProjectSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $projects = [
            [
                'category_id'       => 1,
                'sub_category_id'   => 1,
                'country_id'        => '1',
                'name_en'           => 'City Water Supply Expansion',
                'contractor'        => 'AquaBuild Co.',
                'contractor_amount' => 1250000.00,
                'cost'              => 1500000.00,
                'quantity'          => 1,
                'project_type'      => 'infrastructure',
                'status'            => 'active',
                'is_bank_detail'    => true,
                'bank_details'      => 'Bank: National Bank | IBAN: SA0000000000000000001 | Account: 1234567890',
                'display_on'        => json_encode(['website', 'app']),
                'description_en'    => 'Expansion of the city water supply network covering 5 new districts with modern pipeline infrastructure.',
                'image'             => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'category_id'       => 1,
                'sub_category_id'   => 2,
                'country_id'        => '1',
                'name_en'           => 'Central Sewage Treatment Plant',
                'contractor'        => 'EnviroTech Ltd.',
                'contractor_amount' => 3200000.00,
                'cost'              => 3800000.00,
                'quantity'          => 1,
                'project_type'      => 'infrastructure',
                'status'            => 'active',
                'is_bank_detail'    => false,
                'bank_details'      => null,
                'display_on'        => json_encode(['website', 'cs']),
                'description_en'    => 'Construction of a central sewage treatment plant with a capacity of 50,000 cubic meters per day.',
                'image'             => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'category_id'       => 2,
                'sub_category_id'   => 4,
                'country_id'        => '2',
                'name_en'           => 'Green Valley Apartments',
                'contractor'        => 'HomeCraft Builders',
                'contractor_amount' => 5500000.00,
                'cost'              => 6200000.00,
                'quantity'          => 120,
                'project_type'      => 'building',
                'status'            => 'active',
                'is_bank_detail'    => true,
                'bank_details'      => 'Bank: City Bank | IBAN: SA0000000000000000002 | Account: 9876543210',
                'display_on'        => json_encode(['website', 'app', 'kiosk']),
                'description_en'    => 'A modern residential apartment complex with 120 units, gym, pool, and landscaped gardens.',
                'image'             => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'category_id'       => 2,
                'sub_category_id'   => 5,
                'country_id'        => '2',
                'name_en'           => 'Sunset Villa Community',
                'contractor'        => 'LuxBuild Group',
                'contractor_amount' => 8750000.00,
                'cost'              => 9500000.00,
                'quantity'          => 40,
                'project_type'      => 'building',
                'status'            => 'active',
                'is_bank_detail'    => false,
                'bank_details'      => null,
                'display_on'        => json_encode(['website', 'app']),
                'description_en'    => 'Luxury villa community featuring 40 standalone villas with private pools and smart home systems.',
                'image'             => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'category_id'       => 3,
                'sub_category_id'   => 6,
                'country_id'        => '3',
                'name_en'           => 'Metro Grand Mall',
                'contractor'        => 'CommercePro Constructions',
                'contractor_amount' => 15000000.00,
                'cost'              => 17500000.00,
                'quantity'          => 1,
                'project_type'      => 'building',
                'status'            => 'active',
                'is_bank_detail'    => true,
                'bank_details'      => 'Bank: Trade Bank | IBAN: SA0000000000000000003 | Account: 1122334455',
                'display_on'        => json_encode(['website', 'app', 'cs', 'kiosk']),
                'description_en'    => 'A large-scale shopping mall with 300+ retail outlets, food court, cinema, and parking for 2,000 vehicles.',
                'image'             => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'category_id'       => 4,
                'sub_category_id'   => 8,
                'country_id'        => '1',
                'name_en'           => 'North Industrial Manufacturing Hub',
                'contractor'        => 'IndustrialCore Inc.',
                'contractor_amount' => 22000000.00,
                'cost'              => 25000000.00,
                'quantity'          => 3,
                'project_type'      => 'industrial',
                'status'            => 'inactive',
                'is_bank_detail'    => false,
                'bank_details'      => null,
                'display_on'        => json_encode(['cs']),
                'description_en'    => 'Development of 3 heavy manufacturing plants with integrated logistics and waste management systems.',
                'image'             => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'category_id'       => 5,
                'sub_category_id'   => 10,
                'country_id'        => '4',
                'name_en'           => 'Eastern Ring Road Phase 2',
                'contractor'        => 'RoadMasters Co.',
                'contractor_amount' => 45000000.00,
                'cost'              => 50000000.00,
                'quantity'          => 1,
                'project_type'      => 'road',
                'status'            => 'active',
                'is_bank_detail'    => true,
                'bank_details'      => 'Bank: Infrastructure Bank | IBAN: SA0000000000000000004 | Account: 5566778899',
                'display_on'        => json_encode(['website', 'app', 'kiosk']),
                'description_en'    => 'Construction of a 45km dual carriageway highway connecting the eastern industrial zone to the city center.',
                'image'             => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'category_id'       => 5,
                'sub_category_id'   => 11,
                'country_id'        => '4',
                'name_en'           => 'River Crossing Bridge',
                'contractor'        => 'BridgeTech Engineers',
                'contractor_amount' => 18500000.00,
                'cost'              => 21000000.00,
                'quantity'          => 1,
                'project_type'      => 'road',
                'status'            => 'active',
                'is_bank_detail'    => false,
                'bank_details'      => null,
                'display_on'        => json_encode(['website', 'cs']),
                'description_en'    => 'Design and construction of a 600-meter cable-stayed bridge over the main river with 4 traffic lanes.',
                'image'             => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
        ];

        DB::table('projects')->insert($projects);
    }
}
